const $ = (selector, parent = document) => parent.querySelector(selector);
const $$ = (selector, parent = document) => [...parent.querySelectorAll(selector)];

const copy = {
  en: {
    nav: ['Products', 'Templates', 'Solutions', 'Pricing'], login: 'Sign in', create: 'Create your CV',
    eyebrow: 'CAREER PLATFORM · SAUDI ARABIA',
    hero: 'Build the work you’re known for.',
    heroSub: 'One considered place for your CV, portfolio, and the digital work that moves your career forward.',
    start: 'Start building', explore: 'Explore portfolios', talk: 'Talk to us',
    trusted: 'Built for people doing meaningful work.',
    products: 'Career products, designed to connect.',
    productSub: 'Start with a document. Grow into a presence. Your data stays yours the entire way.',
    templates: 'A template should feel like a point of view.',
    templateSub: 'Responsive, bilingual designs that keep the focus on your work — not the layout.',
    cv: 'CV Builder', portfolio: 'Portfolio', bundle: 'Complete identity',
    cvDesc: 'A polished CV that makes the right details easy to find.', portfolioDesc: 'A personal site that gives your work a place to live.', bundleDesc: 'Your complete career system, connected from the first line.',
    choose: 'Choose template', seeAll: 'View all templates',
    work: 'How it works', workTitle: 'From your first detail to your next opportunity.',
    solution: 'Digital solutions', solutionTitle: 'Need something built from scratch?', solutionText: 'We design and build ambitious digital products for businesses with something to say.',
    viewServices: 'Explore our services',
    pricing: 'Simple pricing. Serious value.',
    priceSub: 'Everything you need to show up professionally — without the subscription trap.',
    popular: 'MOST POPULAR', select: 'Select plan', custom: 'Need a custom design?', customText: 'Work directly with the EcoTrove team on a one-of-one CV or portfolio.', whatsapp: 'Talk on WhatsApp',
    footer: 'A better home for the work that defines you.',
    editor: 'CV Editor', preview: 'Preview', details: 'Your details', save: 'Saved just now', download: 'Download PDF',
    personal: 'Personal info', experience: 'Experience', education: 'Education', skills: 'Skills', projects: 'Projects',
    chooseTemplate: 'Choose a template', dashboard: 'Your workspace', welcome: 'Good afternoon, Ahmed.',
    dashboardSub: 'Everything you need to keep your professional presence moving.',
    active: 'ACTIVE', newCV: 'New CV', publish: 'Publish portfolio', language: 'العربية'
  },
  ar: {
    nav: ['المنتجات', 'القوالب', 'الحلول الرقمية', 'الأسعار'], login: 'تسجيل الدخول', create: 'أنشئ سيرتك الذاتية',
    eyebrow: 'منصة مهنية · المملكة العربية السعودية', hero: 'ابنِ العمل الذي تُعرف به.',
    heroSub: 'مكان واحد مدروس لسيرتك الذاتية، معرض أعمالك، والعمل الرقمي الذي يدفع مسيرتك إلى الأمام.',
    start: 'ابدأ الآن', explore: 'استكشف المعارض', talk: 'تحدث معنا', trusted: 'مصمم لمن يصنعون عملاً ذا أثر.',
    products: 'منتجات مهنية، مصممة لتتكامل.', productSub: 'ابدأ بوثيقة. وتطور إلى حضور متكامل. بياناتك ملكك طوال الطريق.',
    templates: 'القالب الجيد يعكس وجهة نظر.', templateSub: 'تصاميم ثنائية اللغة ومتجاوبة تبقي التركيز على عملك — لا على التنسيق.',
    cv: 'منشئ السيرة الذاتية', portfolio: 'معرض الأعمال', bundle: 'هويتك الكاملة',
    cvDesc: 'سيرة ذاتية متقنة تجعل أهم تفاصيلك سهلة العثور.', portfolioDesc: 'موقع شخصي يمنح عملك مكاناً حقيقياً.', bundleDesc: 'نظامك المهني المتكامل والمتصل منذ السطر الأول.',
    choose: 'اختر القالب', seeAll: 'عرض كل القوالب', work: 'كيف يعمل', workTitle: 'من أول تفاصيلك إلى فرصتك القادمة.',
    solution: 'حلول رقمية', solutionTitle: 'تحتاج شيئاً يُبنى من الصفر؟', solutionText: 'نصمم ونبني منتجات رقمية طموحة للشركات التي لديها ما تقوله.', viewServices: 'استكشف خدماتنا',
    pricing: 'أسعار واضحة. قيمة حقيقية.', priceSub: 'كل ما تحتاجه للظهور باحترافية — دون اشتراكات مرهقة.', popular: 'الأكثر طلباً', select: 'اختر الباقة', custom: 'تحتاج تصميماً مخصصاً؟', customText: 'اعمل مباشرة مع فريق EcoTrove على سيرة أو معرض أعمال فريد.', whatsapp: 'تواصل عبر واتساب',
    footer: 'موطن أفضل للعمل الذي يعبّر عنك.', editor: 'محرر السيرة', preview: 'المعاينة', details: 'بياناتك', save: 'حُفظ الآن', download: 'تحميل PDF',
    personal: 'المعلومات الشخصية', experience: 'الخبرات', education: 'التعليم', skills: 'المهارات', projects: 'المشاريع', chooseTemplate: 'اختر قالباً', dashboard: 'مساحتك', welcome: 'مساء الخير، أحمد.', dashboardSub: 'كل ما تحتاجه لتحريك حضورك المهني للأمام.', active: 'نشط', newCV: 'سيرة جديدة', publish: 'نشر المعرض', language: 'English'
  }
};

const templates = [
  ['Aster', 'Minimal', 'A quiet, editorial resume for considered careers.', 'cream'],
  ['Cedar', 'Technology', 'Structured clarity for technical thinkers.', 'blue'],
  ['Noura', 'Executive', 'An assured format with space for impact.', 'ink'],
  ['Mina', 'Creative', 'A bright, confident canvas for makers.', 'coral'],
  ['Form', 'ATS', 'Simple hierarchy made for easy reading.', 'paper'],
  ['Sahil', 'Modern', 'A contemporary system with Arabic at its core.', 'sand']
];

let state = { lang: 'en', page: 'home', modal: null, selected: 'Aster', mobileMenu: false };
const t = (key) => copy[state.lang][key];
const money = (n) => `${n} ${state.lang === 'ar' ? 'ر.س' : 'SAR'}`;

function header() {
  return `<header><a href="#" class="brand" data-page="home"><i></i>ecotrove</a><nav>${t('nav').map((x,i)=>`<button data-scroll="${['products','templates','solutions','pricing'][i]}">${x}</button>`).join('')}</nav><div class="nav-actions"><button class="lang" data-action="lang">${t('language')}</button><button class="login" data-page="dashboard">${t('login')}</button><button class="button dark small" data-page="marketplace">${t('create')}</button><button class="menu" data-action="menu">☰</button></div></header>${state.mobileMenu ? `<div class="mobile-nav">${t('nav').map(x=>`<button>${x}</button>`).join('')}<button data-action="lang">${t('language')}</button></div>` : ''}`;
}
function templateCard(x, i) { return `<article class="template-card ${x[3]}"><div class="template-sheet"><div class="sheet-top"><span></span><b>${x[0]}</b></div><div class="sheet-lines"><i></i><i></i><i></i><i></i></div><div class="sheet-block"></div></div><div class="template-info"><div><span>${x[1]}</span><h3>${x[0]}</h3></div><button aria-label="Select ${x[0]}" data-template="${x[0]}">↗</button></div></article>`; }
function home() { return `
  <main>
  <section class="hero"><div class="hero-copy"><p class="eyebrow">${t('eyebrow')}</p><h1>${t('hero')}</h1><p class="lead">${t('heroSub')}</p><div class="hero-actions"><button class="button dark" data-page="marketplace">${t('start')} <b>→</b></button><button class="text-button" data-page="portfolio">${t('explore')} <b>↗</b></button></div><p class="trust"><span>✦</span>${t('trusted')}</p></div><div class="hero-art"><div class="hero-circle"></div><div class="hero-card card-one"><small>PROFILE / 01</small><h3>Ahmed<br/>Al-Harbi</h3><p>Product Designer</p><div></div></div><div class="hero-card card-two"><small>RECENT WORK</small><div class="mini-grid"><i></i><i></i><i></i><i></i></div><p>Selected projects</p></div><div class="hero-card card-three"><span>✓</span> Available for work</div></div></section>
  <section class="intro" id="products"><p class="eyebrow">01 / ${t('products')}</p><div class="split-heading"><h2>${t('products')}</h2><p>${t('productSub')}</p></div><div class="product-grid"><article class="product-card"><div class="product-number">01</div><span class="icon">↙</span><h3>${t('cv')}</h3><p>${t('cvDesc')}</p><button data-page="marketplace">${t('choose')} <b>→</b></button></article><article class="product-card dark-card"><div class="product-number">02</div><span class="icon">◈</span><h3>${t('portfolio')}</h3><p>${t('portfolioDesc')}</p><button data-page="portfolio">${t('choose')} <b>→</b></button></article><article class="product-card rust-card"><div class="product-number">03</div><span class="icon">✦</span><h3>${t('bundle')}</h3><p>${t('bundleDesc')}</p><button data-scroll="pricing">${t('choose')} <b>→</b></button></article></div></section>
  <section class="templates" id="templates"><div class="section-top"><div><p class="eyebrow">02 / TEMPLATES</p><h2>${t('templates')}</h2></div><button class="text-button" data-page="marketplace">${t('seeAll')} <b>→</b></button></div><p class="section-description">${t('templateSub')}</p><div class="template-grid">${templates.slice(0,3).map(templateCard).join('')}</div></section>
  <section class="how"><p class="eyebrow">03 / ${t('work')}</p><h2>${t('workTitle')}</h2><div class="steps"><article><b>01</b><h3>Choose your foundation</h3><p>Start with a template that feels like you.</p></article><article><b>02</b><h3>Make it your own</h3><p>Add your work once. Switch styles whenever you want.</p></article><article><b>03</b><h3>Put it into the world</h3><p>Download your CV or publish a portfolio that lasts.</p></article></div></section>
  <section class="solutions" id="solutions"><div><p class="eyebrow">04 / ${t('solution')}</p><h2>${t('solutionTitle')}</h2><p>${t('solutionText')}</p><button class="button light" data-action="contact">${t('viewServices')} <b>→</b></button></div><div class="solution-list">${['Websites & platforms','E-commerce experiences','Mobile applications','Brand & product design'].map((x,i)=>`<button data-action="contact"><span>0${i+1}</span>${x}<b>↗</b></button>`).join('')}</div></section>
  <section class="pricing" id="pricing"><p class="eyebrow">05 / PRICING</p><h2>${t('pricing')}</h2><p class="section-description">${t('priceSub')}</p><div class="price-grid">${[[t('cv'),119,'A focused CV builder and professional PDF export.'],[t('bundle'),249,'CV, portfolio and a full year of portfolio hosting.',true],[t('portfolio'),159,'A published personal site with hosting for one year.']].map(x=>`<article class="price-card ${x[3]?'featured':''}">${x[3]?`<span class="popular">${t('popular')}</span>`:''}<h3>${x[0]}</h3><strong>${money(x[1])}</strong><small>${x[1]===249 ? `Save ${money(29)}` : 'one time'}</small><p>${x[2]}</p><button class="button ${x[3]?'dark':'outline'}" data-page="marketplace">${t('select')}</button></article>`).join('')}</div><div class="custom-line"><div><h3>${t('custom')}</h3><p>${t('customText')}</p></div><button class="button outline" data-action="contact">${t('whatsapp')} ↗</button></div></section>
  </main>`; }
function marketplace() { return `<main class="app-page"><div class="page-heading"><button class="back" data-page="home">← Back</button><p class="eyebrow">TEMPLATE LIBRARY</p><h1>${t('chooseTemplate')}</h1><p>Built as real, flexible layouts. Your content stays when you change direction.</p></div><div class="filters"><button class="active">All templates</button><button>Minimal</button><button>Modern</button><button>Executive</button><button>Creative</button><button>ATS friendly</button><label>⌕ <input placeholder="Search templates" /></label></div><div class="marketplace-grid">${templates.concat(templates).map(templateCard).join('')}</div></main>`; }
function editor() { return `<main class="editor"><aside class="editor-sidebar"><a class="brand"><i></i>ecotrove</a><div class="editor-title"><span>←</span><div><small>${t('editor')}</small><h3>Senior Product Designer</h3></div></div><div class="save-status"><i></i>${t('save')}</div><div class="editor-tabs"><button class="active">${t('details')}</button><button>${t('preview')}</button></div><div class="form-section"><h4>${t('personal')}</h4><label>Full name<input value="Ahmed Al-Harbi" /></label><label>Professional title<input value="Senior Product Designer" /></label><label>About you<textarea>Designer focused on useful digital products and careful systems.</textarea></label></div><div class="accordion">${[t('experience'),t('education'),t('skills'),t('projects')].map((x,i)=>`<button><span>${['↗','◫','✦','□'][i]}</span>${x}<b>+</b></button>`).join('')}</div></aside><section class="editor-main"><div class="editor-toolbar"><button data-page="marketplace">▦ ${state.selected}</button><span></span><button>↶</button><button>↷</button><button class="button dark small" data-action="download">↓ ${t('download')}</button></div><div class="paper-wrap"><article class="cv-paper"><div class="cv-head"><div><p>Ahmed Al-Harbi</p><h1>Senior<br/>Product Designer</h1></div><div class="cv-photo">A</div></div><div class="cv-rule"></div><div class="cv-two"><section><h4>Profile</h4><p>Designer focused on useful digital products and careful systems. I connect product thinking to details that make experiences feel clear and human.</p><h4>Contact</h4><p>ahmed@ecotrove.sa<br/>Riyadh, Saudi Arabia<br/>linkedin.com/in/ahmed</p><h4>Skills</h4><p>Product strategy<br/>UX / UI design<br/>Design systems<br/>Prototyping</p></section><section><h4>Experience</h4><article><small>2022 — Present</small><h3>Lead Product Designer</h3><b>Amana · Riyadh</b><p>Leading experience design across a growing financial platform, from core product journeys to a shared design system.</p></article><article><small>2019 — 2022</small><h3>Product Designer</h3><b>Sanabil · Riyadh</b><p>Designed clear, resilient interfaces for a suite of tools used by operations teams.</p></article><h4>Education</h4><article><small>2015 — 2019</small><h3>BSc, Visual Communication</h3><b>Prince Sultan University</b></article></section></div></article></div></section></main>`; }
function portfolio() { return `<main class="portfolio-page"><div class="portfolio-top"><button data-page="home">← EcoTrove</button><span>Preview mode</span><button class="button dark small" data-page="dashboard">Save & publish</button></div><section class="personal-site"><nav><b>AHMED<span>.</span></b><div>Work &nbsp;&nbsp; About &nbsp;&nbsp; Notes</div><button>Let's talk ↗</button></nav><div class="site-hero"><p>Independent product designer</p><h1>I turn complex<br/>ideas into calm,<br/><em>useful products.</em></h1><div class="site-portrait"><div class="portrait-dot"></div><span>Riyadh, SA<br/>2026</span></div></div><div class="site-work"><span>SELECTED WORK / 2023—2026</span><div class="work-card"><div class="work-pic"></div><h2>Making healthcare feel human</h2><p>Product strategy · Design systems · 2025</p></div></div></section></main>`; }
function dashboard() { return `<main class="dashboard"><aside class="dash-nav"><a class="brand"><i></i>ecotrove</a><p>WORKSPACE</p>${['Overview','My CVs','My portfolios','Orders & billing','Hosting','Settings'].map((x,i)=>`<button class="${i===0?'active':''}">${x}</button>`).join('')}<div><p>HELP</p><button>Support</button><button data-page="home">Sign out</button></div></aside><section class="dash-main"><div class="dash-top"><div><p class="eyebrow">${t('dashboard')}</p><h1>${t('welcome')}</h1><p>${t('dashboardSub')}</p></div><button class="button dark" data-page="marketplace">+ ${t('newCV')}</button></div><div class="stat-grid"><article><span>YOUR CVS</span><strong>02</strong><small>1 updated this week</small></article><article><span>PORTFOLIOS</span><strong>01</strong><small class="green">● ${t('active')}</small></article><article><span>PROFILE VIEWS</span><strong>248</strong><small>+18% this month</small></article></div><div class="dash-section"><div><h2>Recent work</h2><button>View all →</button></div><div class="recent-grid"><article class="recent-cv"><div class="mini-cv"><b>AHMED AL-HARBI</b><i></i><i></i><i></i></div><div><span>CV · ${state.selected}</span><h3>Senior Product Designer</h3><p>Edited 4 hours ago</p><button data-page="editor">Continue editing →</button></div></article><article class="recent-portfolio"><div class="mini-site"><b>AHMED.</b><i></i><i></i></div><div><span>PORTFOLIO · ${t('active')}</span><h3>ahmedalharbi.sa</h3><p>Published 3 days ago</p><button data-page="portfolio">View site ↗</button></div></article></div></div></section></main>`; }
function footer() {return `<footer><div><a class="brand"><i></i>ecotrove</a><p>${t('footer')}</p></div><div class="footer-links"><div><b>Products</b><a>CV Builder</a><a>Portfolio Builder</a><a>Pricing</a></div><div><b>Company</b><a>About</a><a>Digital solutions</a><a>Contact</a></div><div><b>Follow</b><a>Instagram</a><a>LinkedIn</a><a>WhatsApp</a></div></div><small>© 2026 EcoTrove. Built in Saudi Arabia.</small></footer>`}
function modal() { return state.modal ? `<div class="modal-backdrop" data-action="close"><div class="modal" onclick="event.stopPropagation()"><button class="modal-close" data-action="close">×</button><p class="eyebrow">ECOTROVE CUSTOM STUDIO</p><h2>${t('custom')}</h2><p>Our team works with you directly to make a distinctive, tailored CV or portfolio. Start a direct conversation and we’ll take it from there.</p><button class="button dark full" data-action="whatsapp">◉ ${t('whatsapp')}</button><small>We’ll open WhatsApp without a pre-written message.</small></div></div>` : ''}
function render() { const app = $('#app'); const body = state.page === 'home' ? home()+footer() : state.page === 'marketplace' ? marketplace()+footer() : state.page === 'editor' ? editor() : state.page === 'portfolio' ? portfolio() : dashboard(); app.innerHTML = `${state.page !== 'editor' && state.page !== 'portfolio' && state.page !== 'dashboard' ? header() : ''}${body}${modal()}`; document.documentElement.lang=state.lang; document.documentElement.dir=state.lang === 'ar' ? 'rtl' : 'ltr'; document.body.className=state.page; window.scrollTo({top:0,behavior:'instant'}); }
document.addEventListener('click', (e) => { const el=e.target.closest('[data-page],[data-action],[data-template],[data-scroll]'); if(!el)return; if(el.dataset.page){state.page=el.dataset.page;state.mobileMenu=false;render()} if(el.dataset.template){state.selected=el.dataset.template;state.page='editor';render()} if(el.dataset.action==='lang'){state.lang=state.lang==='en'?'ar':'en';render()} if(el.dataset.action==='menu'){state.mobileMenu=!state.mobileMenu;render()} if(el.dataset.action==='contact'){state.modal=true;render()} if(el.dataset.action==='close'){state.modal=false;render()} if(el.dataset.action==='whatsapp'){window.open('https://wa.me/966500000000','_blank','noopener')} if(el.dataset.action==='download'){alert('Your PDF export has been queued. In production this connects to the PDF service.')} if(el.dataset.scroll){$('#'+el.dataset.scroll)?.scrollIntoView({behavior:'smooth'})} });
render();
